# Generated by Django 2.1.4 on 2018-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_remove_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('s', 'soltero'), ('c', 'casado'), ('v', 'viudo'), ('d', 'divorsiado')], max_length=15),
        ),
    ]
