# Generated by Django 2.1.4 on 2018-12-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20181224_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
